var DEFAULT_SETTINGS = {
	"Command": "!trivia",
	"Cooldown": 30.0,
	"AnswerCommand": "!answer",
	"QuestionResponse": "::TRIVIA QUESTION:: CATEGORY: $triviacategory :: DIFFICULTY: $triviadifficulty :: POINTS: $triviapoints\\n$triviaquestion :: $triviaanswers Use $triviaanswercommand <number> to answer",
	"CorrectResponse": "@$username -> You got the correct answer: '$triviacorrect' and have been awarded $triviapoints $currencyname.",
	"ClearResponse": "@$username -> You have cleared the current trivia question. The correct answer was '$triviacorrect'.",
	"AlreadyAnsweredResponse": "@$username -> You have already made an incorrect guess on the current question.",
	"IncorrectResponse": "@$username -> That is not the correct answer.",
	"UnknownAnswerResponse": "@$username -> You should use $triviaanswercommand <number> to answer.",
	"QuestionCategory": "Any",
	"QuestionDifficulty": "Any",
	"QuestionType": "Any",
	"TimeToAnswer": 60.0,
	"PointsEasy": 100.0,
	"PointsMedium": 250.0,
	"PointsHard": 500.0,
	"TimeoutResponse": "No one got the correct answer. The correct answer was '$triviacorrect'.",
	"QuestionColor": "rgba(255, 255, 255, 1)",
	"AnswerColor": "rgba(255, 255, 255, 1)",
	"UserColor": "rgba(255, 0, 0, 1)",
	"HelpColor": "rgba(200, 200, 200, 1)",
	"CommandColor": "rgba(153, 74, 0, 1)"
};
